#
### lazygit
#

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

#
### recycle-bin
#

[[mgr.prepend_keymap]]
on = ["T"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

#
### restore
#

[[mgr.prepend_keymap]]
on = ["R", "u"]
run = "plugin restore"
desc = "Restore last deleted"

    # Select files/folders to restore. Input item index or range separated by comma:
    # - Restore a trashed file:
    #      What file to restore [0..4]: 4
    # - Restore multiple trashed files separated by comma, also support range:
    #      What file to restore [0..3]: 0-2, 3

    # This will throw error when there is existed file/folder
[[mgr.prepend_keymap]]
on = [ "R", "U" ]
run = "plugin restore -- --interactive"
desc = "Restore (Interactive)"
    # Or auto overwrite existed file/folder
[[mgr.prepend_keymap]]
on = [ "R", "O"]
run = "plugin restore -- --interactive --interactive-overwrite"
desc = "Restore (Interactive overwrite)"
