# o = open in qutebrowser
[[mgr.prepend_keymap]]
on   = ["o", "q"]
run  = "shell --orphan -- qutebrowser %*"
desc = "Open Qutebrowser"

# l = open in librewolf
[[mgr.prepend_keymap]]
on   = ["o", "l"]
run  = "shell --orphan -- libreoffice %*"
desc = "Open Librewolf"

# p = open in zathura
[[mgr.prepend_keymap]]
on   = ["o", "z"]
run  = "shell --orphan -- zathura %*"
desc = "Open Zathura"

# N = nvim in a NEW foot window (not floating, just new window)
[[mgr.prepend_keymap]]
on   = ["o", "n"]
run  = "shell --orphan -- foot -T nvim nvim %*"
desc = "Open Neovim"


#
### sudo
#
[[mgr.prepend_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

[[mgr.prepend_keymap]]
on = ["R", "m"]
run = "plugin sudo -- chmod"
desc = "sudo chmod"

#
### lazygit
#
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

#
### recycle-bin
#
[[mgr.prepend_keymap]]
on = ["T"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

#
### restore
#
[[mgr.prepend_keymap]]
on = ["B", "u"]
run = "plugin restore"
desc = "Restore last deleted"

[[mgr.prepend_keymap]]
on = [ "B", "U" ]
run = "plugin restore -- --interactive"
desc = "Restore (Interactive)"

[[mgr.prepend_keymap]]
on = [ "B", "O" ]
run = "plugin restore -- --interactive --interactive-overwrite"
desc = "Restore (Interactive overwrite)"
