# o = open in qutebrowser
[[mgr.prepend_keymap]]
on   = "b"
run  = "shell --orphan -- qutebrowser \"%h\""
desc = "Open hovered in qutebrowser"

# l = open in librewolf
[[mgr.prepend_keymap]]
on   = "l"
run  = "shell --orphan -- libreoffice \"%h\""
desc = "Open hovered in librewolf"

# p = open in zathura
[[mgr.prepend_keymap]]
on   = "p"
run  = "shell --orphan -- zathura \"%h\""
desc = "Open hovered in zathura"

# n = edit in nvim (blocking)
[[mgr.prepend_keymap]]
on   = "v"
run  = "shell --block -- nvim \"%h\""
desc = "Edit hovered in Neovim"

# N = nvim in a NEW foot window (not floating, just new window)
[[mgr.prepend_keymap]]
on   = "V"
run  = "shell --orphan -- foot -T nvim nvim \"%h\""
desc = "Open hovered in Neovim (new foot window)"


#
### sudo
#
[[mgr.prepend_keymap]]
on = ["R", "p", "p"]
run = "plugin sudo -- paste"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "P"]
run = "plugin sudo -- paste --force"
desc = "sudo paste"

[[mgr.prepend_keymap]]
on = ["R", "r"]
run = "plugin sudo -- rename"
desc = "sudo rename"

[[mgr.prepend_keymap]]
on = ["R", "p", "l"]
run = "plugin sudo -- link"
desc = "sudo link"

[[mgr.prepend_keymap]]
on = ["R", "p", "r"]
run = "plugin sudo -- link --relative"
desc = "sudo link relative path"

[[mgr.prepend_keymap]]
on = ["R", "p", "L"]
run = "plugin sudo -- hardlink"
desc = "sudo hardlink"

[[mgr.prepend_keymap]]
on = ["R", "a"]
run = "plugin sudo -- create"
desc = "sudo create"

[[mgr.prepend_keymap]]
on = ["R", "d"]
run = "plugin sudo -- remove"
desc = "sudo trash"

[[mgr.prepend_keymap]]
on = ["R", "D"]
run = "plugin sudo -- remove --permanently"
desc = "sudo delete"

[[mgr.prepend_keymap]]
on = ["R", "m"]
run = "plugin sudo -- chmod"
desc = "sudo chmod"

#
### lazygit
#
[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

#
### recycle-bin
#
[[mgr.prepend_keymap]]
on = ["T"]
run = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

#
### restore
#
[[mgr.prepend_keymap]]
on = ["B", "u"]
run = "plugin restore"
desc = "Restore last deleted"

[[mgr.prepend_keymap]]
on = [ "B", "U" ]
run = "plugin restore -- --interactive"
desc = "Restore (Interactive)"

[[mgr.prepend_keymap]]
on = [ "B", "O" ]
run = "plugin restore -- --interactive --interactive-overwrite"
desc = "Restore (Interactive overwrite)"
